name: CI
on: push
jobs:
  build:
    runs-on: ${{matrix.runs-on}}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
        python-version: [3.6, 3.8, pypy3]
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}
      - uses: ros-tooling/setup-ros@master
      - uses: ros-tooling/action-ros-ci@master
        with:
          package-name: ament_copyright
          target-ros2-distro: foxy
